version: '3.9'

services:
  postgres:
    container_name: postgres-blackpearl
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: blackpearl
      POSTGRES_USER: blackpearl_user
      POSTGRES_DB: postgres-blackpearl
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
