# Generated by Django 4.2 on 2023-04-29 18:30

from django.db import migrations, models
import django.db.models.deletion




class Migration(migrations.Migration):
    initial = True

    dependencies = [

    ]

    operations = [

        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nomecompleto', models.CharField(max_length=300, verbose_name='Nome Completo')),
                ('nomedamae', models.CharField(max_length=300, verbose_name='Nome da Mãe')),
                ('dataNascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo',
                 models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('identidade', models.CharField(default='', max_length=20, verbose_name='Identidade')),
                ('orgemissor', models.CharField(choices=[('SSP', 'Secretaria de Segurança Pública'),
                                                         ('SSPDS', 'Secretaria de Segurança Pública e Defesa Social'),
                                                         ('PF', 'Polícia Federal'), ('PC', 'Polícia Civil'),
                                                         ('XXX', 'Orgão Estrangeiro'), ('ZZZ', 'Outro')], default='',
                                                max_length=6, verbose_name='Órgão Emissor')),
                ('estadocivil', models.CharField(
                    choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'),
                             ('U', 'União Estável'), ('O', 'Outro')], default='', max_length=2,
                    verbose_name='Estado Civil')),
                ('empresaemquetrabalha', models.CharField(max_length=100, verbose_name='Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('dddNumeroContato', models.CharField(max_length=2, verbose_name='DDD')),
                ('numeroContato', models.CharField(max_length=9, verbose_name='Celular')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('num', models.IntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(
                    choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'),
                             ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'),
                             ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'),
                             ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'),
                             ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'),
                             ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'),
                             ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'),
                             ('TO', 'Tocantins')], default='', max_length=2, verbose_name='Estado (UF)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da empresa')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado de atuação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUploadExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nomecompleto', models.CharField(max_length=300, verbose_name='Nome Completo')),
                ('nomedamae', models.CharField(max_length=300, verbose_name='Nome da Mãe')),
                ('dataNascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo',
                 models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('identidade', models.CharField(default='', max_length=20, verbose_name='Identidade')),
                ('orgemissor', models.CharField(choices=[('SSP', 'Secretaria de Segurança Pública'),
                                                         ('SSPDS', 'Secretaria de Segurança Pública e Defesa Social'),
                                                         ('PF', 'Polícia Federal'), ('PC', 'Polícia Civil'),
                                                         ('XXX', 'Orgão Estrangeiro'), ('ZZZ', 'Outro')], default='',
                                                max_length=6, verbose_name='Órgão Emissor')),
                ('grauparentesco', models.CharField(
                    choices=[('P', 'Pai'), ('M', 'Mãe'), ('F', 'Filho(a)'), ('C', 'Cônjuge'), ('I', 'Irmão(ã)'),
                             ('O', 'Outro')], default='', max_length=6, verbose_name='Órgão Emissor')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes',
                                              to='associados.associado')),
            ],
            options={
                'abstract': False,
            },
        ),

    ]
