# Generated by Django 4.2 on 2023-10-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='associacao',
            field=models.CharField(choices=[('ag', 'Agredado(a)'), ('fiativo', 'Filiado(a) da Ativa'), ('fiaposent', 'Filiado(a) Aposentado(a)'), ('func', 'Funcionário(a) da Associação'), ('desfi', 'Desfiliado(a)'), ('outros', 'Outros')], default='', max_length=50, verbose_name='Associação'),
        ),
    ]
