# Generated by Django 4.2 on 2023-05-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='estadocivil',
            field=models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'), ('U', 'União Estável'), ('O', 'Outro')], default='', max_length=2, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='identidade',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Identidade'),
        ),
        migrations.AlterField(
            model_name='associado',
            name='orgemissor',
            field=models.CharField(blank=True, choices=[('SSP', 'Secretaria de Segurança Pública'), ('SSPDS', 'Secretaria de Segurança Pública e Defesa Social'), ('PF', 'Polícia Federal'), ('PC', 'Polícia Civil'), ('XXX', 'Orgão Estrangeiro'), ('ZZZ', 'Outro')], default='', max_length=6, verbose_name='Órgão Emissor'),
        ),
    ]
