# Generated by Django 4.2 on 2023-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='matricula',
            field=models.IntegerField(blank=True, default=0, verbose_name='Matricula'),
        ),
    ]
