# Generated by Django 4.2 on 2023-04-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0002_alter_associado_datanascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='')),
            ],
        ),
    ]
