# Generated by Django 4.2 on 2023-04-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0002_associado_associacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='empresaemquetrabalha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='associados.empresa'),
        ),
    ]
