# Generated by Django 4.2 on 2023-04-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_fileuploadexcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FileUploadExcel',
        ),
    ]
