# Generated by Django 4.2 on 2023-04-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_alter_associado_empresaemquetrabalha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associado',
            old_name='empresaemquetrabalha',
            new_name='empresa',
        ),
    ]
