# Generated by Django 4.2 on 2023-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0004_rename_empresaemquetrabalha_associado_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='grauparentesco',
            field=models.CharField(choices=[('P', 'Pai'), ('M', 'Mãe'), ('F', 'Filho(a)'), ('C', 'Cônjuge'), ('I', 'Irmão(ã)'), ('O', 'Outro')], default='', max_length=6, verbose_name='Grau de Parentesco'),
        ),
    ]
