# Generated by Django 4.2 on 2023-05-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0007_alter_associado_dataassociacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='matricula',
            field=models.IntegerField(null=True, verbose_name='Matricula'),
        ),
    ]
