# Generated by Django 4.2 on 2023-05-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0008_associado_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='identidade',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Identidade'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='orgemissor',
            field=models.CharField(blank=True, choices=[('SSP', 'Secretaria de Segurança Pública'), ('SSPDS', 'Secretaria de Segurança Pública e Defesa Social'), ('PF', 'Polícia Federal'), ('PC', 'Polícia Civil'), ('XXX', 'Orgão Estrangeiro'), ('ZZZ', 'Outro')], default='', max_length=6, verbose_name='Órgão Emissor'),
        ),
    ]
