# Generated by Django 4.2 on 2023-05-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0009_alter_dependente_identidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='dataNascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
