# Generated by Django 4.2 on 2023-06-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoConvenioVolus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(default='Convênio Volus', max_length=20, verbose_name='Nome do Cartão')),
                ('valorLimite', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Limite')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('SUSPENSO', 'SUSPENSO'), ('CANCELADO', 'CANCELADO')], max_length=20, verbose_name='Status')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartaovolus', to='associados.associado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Otica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(choices=[('Ótica Telegrafo', 'Ótica Telegrafo'), ('Ótica Progressiva', 'Ótica Progressiva')], max_length=40, verbose_name='Nome da Ótica')),
                ('cnpj', models.CharField(max_length=40, verbose_name='CNPJ')),
                ('valorCompra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Compra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoOdontologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(default='Uniodonto Belém', max_length=20, verbose_name='Nome')),
                ('numContrato', models.CharField(default='00319', max_length=20, verbose_name='Número do contrato')),
                ('cnpj', models.CharField(default='15.308.521/0001-88', max_length=40, verbose_name='CNPJ')),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Unitário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(choices=[('Unimed - Max Nacional', 'Unimed - Max Nacional'), ('Unimed - Grupo de Municipios', 'Unimed - Grupo de Municipios')], max_length=100, verbose_name='Nome do Plano')),
                ('cnpj', models.CharField(default='04.201.372/0001-37', max_length=40, verbose_name='CNPJ')),
                ('contrato', models.CharField(max_length=10, verbose_name='Número do Contrato')),
                ('segmentacao', models.CharField(choices=[('Apartamento', 'Apartamento'), ('Enfermaria', 'Enfermaria')], max_length=20, verbose_name='Segmentação')),
                ('valorAtendimentoDomiciliar', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor do Atendimento Domiciliar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxasAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('grupos', models.CharField(choices=[('ag', 'Agredado(a)'), ('fiativo', 'Filiado(a) da Ativa'), ('fiaposent', 'Filiado(a) Aposentado(a)'), ('desfi', 'Desfiliado(a)'), ('outros', 'Cartão')], max_length=20, verbose_name='Grupo')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Percetual da Taxa Administrativa (%)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValoresPorFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('idadeMin', models.IntegerField(verbose_name='Idade Minima')),
                ('idadeMax', models.IntegerField(verbose_name='Idade Max')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor da Faixa')),
                ('planoSaude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='convenios.planosaude')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Fatura')),
                ('valorComTaxa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor da Fatura com a Taxa Adm')),
                ('competencia', models.DateField(verbose_name='Competência')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='convenios.cartaoconveniovolus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoPlanoOdontologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('datacontrato', models.DateField(verbose_name='Data da Contratação')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor')),
                ('contratante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_odontologico', to='associados.associado')),
                ('plano_odontologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.planoodontologico')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
