# Generated by Django 4.2 on 2023-05-05 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(choices=[('Unimed - Max Nacional', 'Unimed - Max Nacional'), ('Unimed - Grupo de Municipios', 'Unimed - Grupo de Municipios')], max_length=100, verbose_name='Nome do Plano')),
                ('contrato', models.CharField(max_length=10, verbose_name='Número do Contrato')),
                ('segmentacao', models.CharField(choices=[('Apartamento', 'Apartamento'), ('Enfermaria', 'Enfermaria')], max_length=20, verbose_name='Segmentação')),
                ('atendimentoDomiciliar', models.BooleanField(default=False, verbose_name='Contratado?')),
                ('valorAtendimentoDomiciliar', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor do Atendimento Domiciliar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaixaIdadeValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('idadeMin', models.IntegerField(verbose_name='Idade Minima')),
                ('idadeMax', models.IntegerField(verbose_name='Idade Max')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor da Faixa')),
                ('planoSaude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='convenios.planosaude')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
