# Generated by Django 4.2 on 2023-05-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faixaidadevalores',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor da Faixa'),
        ),
    ]
