# Generated by Django 4.2 on 2023-05-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratacoes', to='associados.associado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContratacaoDependentePlanoOdontologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='planoodontologico',
            name='numContrato',
            field=models.CharField(default='00319', max_length=20, verbose_name='Número do contrato'),
        ),
        migrations.CreateModel(
            name='ContratacaoPlanoOdontologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('contratacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_odontologico', to='convenios.contratacao')),
                ('dependentes', models.ManyToManyField(through='convenios.ContratacaoDependentePlanoOdontologico', to='associados.dependente')),
                ('plano_odontologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.planoodontologico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contratacaodependenteplanoodontologico',
            name='contratacao_plano_odontologico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.contratacaoplanoodontologico'),
        ),
        migrations.AddField(
            model_name='contratacaodependenteplanoodontologico',
            name='dependente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associados.dependente'),
        ),
    ]
