# Generated by Django 4.2 on 2023-10-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoplanosaudedependente',
            name='dependente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_saude', to='associados.dependente'),
        ),
    ]
