# Generated by Django 4.2 on 2023-06-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaoconveniovolus',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='contratoplanoodontologico',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='contratoplanoodontologico',
            name='contratante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_odontologicos', to='associados.associado'),
        ),
        migrations.AlterField(
            model_name='contratoplanoodontologicodependente',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='faturacartao',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='otica',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='planoodontologico',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='planosaude',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='taxasadministrativa',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='valoresporfaixa',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?'),
        ),
        migrations.CreateModel(
            name='ContratoPlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?')),
                ('atendimentoDomiciliar', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Atendimento Domiciliar')),
                ('dataInicio', models.DateField(verbose_name='Data da Contratação')),
                ('dataFim', models.DateField(blank=True, null=True, verbose_name='Data do Cancelamento')),
                ('formaPagamento', models.CharField(choices=[('Boleto Bancário', 'Boleto Bancário'), ('Desconto em folha', 'Desconto em folha')], max_length=20, verbose_name='Forma de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Contrato')),
                ('contratante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_saude', to='associados.associado')),
                ('faixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='convenios.valoresporfaixa')),
                ('planoSaude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='convenios.planosaude')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
