# Generated by Django 4.2 on 2023-06-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planosaude',
            name='valorAtendimentoTelefonico',
            field=models.DecimalField(decimal_places=2, default=3.2, max_digits=5, verbose_name='Valor do Atendimento Telefonico'),
        ),
    ]
