# Generated by Django 4.2 on 2023-06-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_alter_cartaoconveniovolus_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoplanosaude',
            name='formaPagamento',
            field=models.CharField(choices=[('Boleto Bancário', 'Boleto Bancário'), ('Desconto em folha', 'Desconto em folha'), ('Isento', 'Isento')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
