# Generated by Django 4.2 on 2023-10-03 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_alter_contratoplanosaudedependente_dependente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContratoPlanoOdontologicoDependente',
        ),
    ]
