# Generated by Django 4.2 on 2023-05-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
        ('convenios', '0002_contratacao_contratacaodependenteplanoodontologico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacaoplanoodontologico',
            name='contratacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_odontologico', to='associados.associado'),
        ),
        migrations.DeleteModel(
            name='Contratacao',
        ),
    ]
