# Generated by Django 4.2 on 2023-05-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_alter_faixaidadevalores_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoVolus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('valorLimite', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Limite')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('SUSPENSO', 'SUSPENSO'), ('CANCELADO', 'CANCELADO')], max_length=20, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanoOdontologicoUniodonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(default='Uniodonto Belém', max_length=20, verbose_name='Nome')),
                ('numContrato', models.CharField(max_length=20, verbose_name='Número do contrato')),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Unitário')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('SUSPENSO', 'SUSPENSO'), ('CANCELADO', 'CANCELADO')], max_length=20, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
