# Generated by Django 4.2 on 2023-05-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0003_cartaovolus_planoodontologicouniodonto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaixaIdadeValores',
            new_name='FaixaIdadeValor',
        ),
        migrations.RemoveField(
            model_name='planoodontologicouniodonto',
            name='status',
        ),
        migrations.AddField(
            model_name='planoodontologicouniodonto',
            name='cnpj',
            field=models.CharField(default='15.308.521/0001-88', max_length=40, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='planosaude',
            name='cnpj',
            field=models.CharField(default='04.201.372/0001-37', max_length=40, verbose_name='CNPJ'),
        ),
    ]
