# Generated by Django 4.2 on 2023-10-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0003_delete_contratoplanoodontologicodependente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoplanoodontologico',
            name='quantidadeDependententes',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Dependentes'),
        ),
    ]
