# Generated by Django 4.2 on 2023-05-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0004_rename_faixaidadevalores_faixaidadevalor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanoOdontologicoUniodonto',
            new_name='PlanoOdontologico',
        ),
    ]
