# Generated by Django 4.2 on 2023-10-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0004_contratoplanoodontologico_quantidadedependententes'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturacartao',
            name='situacaoFatura',
            field=models.CharField(choices=[('ABERTA', 'ABERTA'), ('PAGA', 'PAGA'), ('CANCELADA', 'CANCELADA')], default='ABERTA', max_length=20, verbose_name='Situação da Fatura'),
        ),
        migrations.AlterField(
            model_name='taxasadministrativa',
            name='grupos',
            field=models.CharField(choices=[('ag', 'Agredado(a)'), ('fiativo', 'Filiado(a) da Ativa'), ('fiaposent', 'Filiado(a) Aposentado(a)'), ('func', 'Funcionário(a) da Associação'), ('desfi', 'Desfiliado(a)'), ('outros', 'Outros')], max_length=20, verbose_name='Grupo'),
        ),
    ]
