# Generated by Django 4.2 on 2023-05-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0004_rename_contratacao_contratacaoplanoodontologico_contratante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratacaodependenteplanoodontologico',
            name='valor',
        ),
    ]
