# Generated by Django 4.2 on 2023-05-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0005_rename_planoodontologicouniodonto_planoodontologico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaixaIdadeValor',
            new_name='ValoresPorFaixa',
        ),
    ]
