# Generated by Django 4.2 on 2023-05-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0005_remove_contratacaodependenteplanoodontologico_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacaoplanoodontologico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor'),
        ),
    ]
