# Generated by Django 4.2 on 2023-10-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0002_alter_associado_associacao'),
        ('convenios', '0005_faturacartao_situacaofatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoplanoodontologico',
            name='quantidadeDependententes',
        ),
        migrations.CreateModel(
            name='DependentePlanoOdontologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('valorComTaxa', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor com Taxa')),
                ('dataInicio', models.DateField(verbose_name='Data de Início')),
                ('dataFim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('contratoTitular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='convenios.contratoplanoodontologico')),
                ('dependente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_odontologico_dependentes', to='associados.dependente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
