# Generated by Django 4.2 on 2023-05-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0006_rename_faixaidadevalor_valoresporfaixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(default='Convênio Volus', max_length=20, verbose_name='Nome do Cartão')),
                ('valorLimite', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Limite')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('SUSPENSO', 'SUSPENSO'), ('CANCELADO', 'CANCELADO')], max_length=20, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CartaoVolus',
        ),
    ]
