# Generated by Django 4.2 on 2023-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0007_alter_contratacaoplanoodontologico_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacaodependenteplanoodontologico',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor'),
        ),
    ]
