# Generated by Django 4.2 on 2023-05-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0007_cartaoconvenio_delete_cartaovolus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(choices=[('Ótica Telegrafo', 'Ótica Telegrafo'), ('Ótica Progressiva', 'Ótica Progressiva')], max_length=40, verbose_name='Nome da Ótica')),
                ('cnpj', models.CharField(max_length=40, verbose_name='CNPJ')),
                ('valorCompra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Compra')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
