# Generated by Django 4.2 on 2023-05-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0008_otica'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('percentual', models.DecimalField(choices=[(15.0, '15%'), (8.0, '8%'), (5.0, '5%')], decimal_places=2, max_digits=8, verbose_name='Percetual da Taxa Administrativa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
