# Generated by Django 4.2 on 2023-05-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0008_contratacaodependenteplanoodontologico_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratacaoplanoodontologico',
            name='dependentes',
        ),
        migrations.DeleteModel(
            name='ContratacaoDependentePlanoOdontologico',
        ),
    ]
