# Generated by Django 4.2 on 2023-05-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0010_cartaoconveniovolus_delete_cartaoconvenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Fatura')),
                ('competencia', models.DateField(verbose_name='Competência')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartao', to='convenios.cartaoconveniovolus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
