# Generated by Django 4.2 on 2023-05-20 03:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0013_contratacaoplanoodontologico_dependentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacaoplanoodontologico',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('32.45'), max_digits=8, null=True, verbose_name='Valor'),
        ),
    ]
