# Generated by Django 4.2 on 2023-05-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0016_alter_taxaadministrativa_percentual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxasAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('convenio', models.CharField(choices=[('Cartão', 'Cartão'), ('Saúde', 'Saúde'), ('Odontológico', 'Odontológico')], max_length=20, verbose_name='Categoria do Convênio')),
                ('grupo', models.CharField(choices=[('ag', 'Agredado(a)'), ('fiativo', 'Filiado(a) da Ativa'), ('fiaposent', 'Filiado(a) Aposentado(a)'), ('desfi', 'Desfiliado(a)')], max_length=20, verbose_name='Grupo')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Percetual da Taxa Administrativa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contratacaodependenteplanoodontologico',
            name='contratacao_plano_odontologico',
        ),
        migrations.RemoveField(
            model_name='contratacaodependenteplanoodontologico',
            name='dependente',
        ),
        migrations.DeleteModel(
            name='TaxaAdministrativa',
        ),
        migrations.DeleteModel(
            name='ContratacaoDependentePlanoOdontologico',
        ),
    ]
