# Generated by Django 4.2 on 2023-05-20 16:32

import admin_kit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0017_taxasadministrativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('convenio', models.CharField(choices=[('Cartão', 'Cartão'), ('Saúde', 'Saúde'), ('Odontológico', 'Odontológico')], max_length=20, verbose_name='Categoria do Convênio')),
                ('grupo', admin_kit.models.MultiSelectField(ajax_source=None, choices=[('ag', 'Agredado(a)'), ('fiativo', 'Filiado(a) da Ativa'), ('fiaposent', 'Filiado(a) Aposentado(a)'), ('desfi', 'Desfiliado(a)')], default_value=None, identifier=None, kit_config={}, max_length=20, seperator='Grupo', source_router=None)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Percetual da Taxa Administrativa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TaxasAdministrativa',
        ),
    ]
