# Generated by Django 4.2 on 2023-05-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0018_taxaadministrativa_delete_taxasadministrativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxaadministrativa',
            name='convenio',
        ),
        migrations.AlterField(
            model_name='taxaadministrativa',
            name='percentual',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Percetual da Taxa Administrativa (%)'),
        ),
    ]
