# Generated by Django 4.2 on 2023-05-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0019_remove_taxaadministrativa_convenio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxasAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('grupos', models.CharField(choices=[('ag', 'Agredado(a)'), ('fiativo', 'Filiado(a) da Ativa'), ('fiaposent', 'Filiado(a) Aposentado(a)'), ('desfi', 'Desfiliado(a)')], max_length=20, verbose_name='Grupo')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Percetual da Taxa Administrativa (%)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TaxaAdministrativa',
        ),
    ]
