# Generated by Django 4.2 on 2023-05-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0021_contratacaodependenteplanoodontologico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContratacaoDependentePlanoOdontologico',
        ),
    ]
