# Generated by Django 4.2 on 2023-06-29 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Destinatário')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome do Destinatário')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('pronomeTratamento', models.CharField(choices=[('Sr.', 'Sr.'), ('Sra.', 'Sra.')], max_length=100, verbose_name='Pronome de Tratamento')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Diretor')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome do Diretor')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('cargo', models.CharField(choices=[('Presidente', 'Presidente'), ('Vice-Presidente', 'Vice-Presidente'), ('1º Tesoureiro', '1º Tesoureiro'), ('2º Tesoureiro', '2º Tesoureiro'), ('1º Secretário', '1º Secretário'), ('2º Secretário', '2º Secretário')], max_length=100, verbose_name='Cargo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Assinatura')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?')),
                ('numeracao', models.IntegerField(verbose_name='Numeração do Ofício')),
                ('dataOficio', models.DateField(verbose_name='Data do Ofício')),
                ('assunto', models.CharField(max_length=200, verbose_name='Assunto')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficios.destinatario', verbose_name='destinatario')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficios.diretor', verbose_name='remetente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
