# Generated by Django 4.2 on 2023-06-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diretor',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
