# Generated by Django 4.2 on 2023-11-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenios', '0006_remove_contratoplanoodontologico_quantidadedependententes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaPlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(help_text='Nome da fatura. Ex: Fatura 01/2020', max_length=100, verbose_name='Nome')),
                ('competencia', models.DateField(help_text='Data de competência da fatura. Ex: 01/2020', verbose_name='Competência')),
                ('valorTotalContratos', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor dos Contratos')),
                ('valorTotalAtendimentoDomiciliar', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Atendimento Domiciliar')),
                ('valorTotalAtendimentoTelefonico', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Atendimento Telefonico')),
                ('valorTotalTaxaAdministrativa', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Taxa Administrativa')),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Total')),
                ('contratos', models.ManyToManyField(related_name='faturas', to='convenios.contratoplanosaude')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
