# Generated by Django 4.2 on 2023-11-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0002_alter_faturaplanosaude_contratos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaturaPlanoSaude',
        ),
    ]
