# Generated by Django 4.2 on 2023-11-29 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenios', '0006_remove_contratoplanoodontologico_quantidadedependententes_and_more'),
        ('cobrancas', '0003_delete_faturaplanosaude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?')),
                ('valorContratado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do contrato')),
                ('dataDoVencimento', models.DateField(verbose_name='Data do vencimento')),
                ('dataDoPagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('situacao', models.CharField(choices=[('A', 'Aberta'), ('P', 'Paga'), ('C', 'Cancelada'), ('V', 'Vencida')], default='A', max_length=1, verbose_name='Situação')),
                ('juros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Multa')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['dataDoVencimento'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaPlanoSaude',
            fields=[
                ('faturacobranca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cobrancas.faturacobranca')),
                ('contratoPlanoSaude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.contratoplanosaude', verbose_name='Contrato do plano de saúde')),
            ],
            options={
                'abstract': False,
            },
            bases=('cobrancas.faturacobranca',),
        ),
        migrations.CreateModel(
            name='CobrancaPlanoOdontologico',
            fields=[
                ('faturacobranca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cobrancas.faturacobranca')),
                ('contratoPlanoOdontologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convenios.contratoplanoodontologico', verbose_name='Contrato do plano odontológico')),
            ],
            options={
                'abstract': False,
            },
            bases=('cobrancas.faturacobranca',),
        ),
    ]
