# Generated by Django 4.2 on 2023-11-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturacobranca',
            name='valorPago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor pago'),
        ),
    ]
