# Generated by Django 4.2 on 2023-12-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0005_faturacobranca_valorpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturacobranca',
            name='juros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Juros'),
        ),
        migrations.AlterField(
            model_name='faturacobranca',
            name='multa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Multa'),
        ),
    ]
