# Generated by Django 4.2 on 2023-12-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0006_alter_faturacobranca_juros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaCobrancaDiasConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Ativo?')),
                ('diaParaGeracaoPlanosDeSaude', models.IntegerField(default=15, verbose_name='Dia para geração dos planos de saúde')),
                ('diaParaGeracaoPlanosOdontologicos', models.IntegerField(default=15, verbose_name='Dia para geração dos planos odontológicos')),
                ('diaParaVencimentoPlanosDeSaude', models.IntegerField(default=10, verbose_name='Dia para vencimento dos planos de saúde')),
                ('diaParaVencimentoPlanosOdontologicos', models.IntegerField(default=10, verbose_name='Dia para vencimento dos planos odontológicos')),
            ],
            options={
                'verbose_name': 'Configuração do dia de cobrança',
                'verbose_name_plural': 'Configurações dos dias de cobrança',
            },
        ),
    ]
