# Generated by Django 4.2 on 2023-12-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0007_faturacobrancadiasconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faturacobrancadiasconfig',
            old_name='diaParaVencimentoPlanosOdontologicos',
            new_name='diaParaVencimentoPlanosOdontologico',
        ),
    ]
