# Generated by Django 4.2 on 2023-12-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0008_rename_diaparavencimentoplanosodontologicos_faturacobrancadiasconfig_diaparavencimentoplanosodontolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faturacobrancadiasconfig',
            old_name='diaParaGeracaoPlanosOdontologicos',
            new_name='diaParaGeracaoPlanosOdontologico',
        ),
    ]
